name: "AttributedString CI"

on:
  push:
    branches:
      - master
      - hotfix
  pull_request:
    branches:
      - '*'

jobs:
  macOS:
    name: Test macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: macOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AttributedString.xcodeproj" -scheme "AttributedString-macOS" -destination "platform=macOS" clean test | xcpretty
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=16.2,name=iPhone 14 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AttributedString.xcodeproj" -scheme "AttributedString-iOS" -destination "${{ matrix.destination }}" clean test | xcpretty
  tvOS:
    name: Test tvOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=16.2,name=Apple TV 4K (2nd generation)"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    steps:
      - uses: actions/checkout@v2
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AttributedString.xcodeproj" -scheme "AttributedString-tvOS" -destination "${{ matrix.destination }}" clean test | xcpretty
  watchOS:
    name: Build watchOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=9.1,name=Apple Watch Series 8 - 45mm"] #, "OS=4.2,name=Apple Watch Series 3 - 42mm", "OS=3.2,name=Apple Watch Series 2 - 42mm"]
    steps:
      - uses: actions/checkout@v2
      - name: watchOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "AttributedString.xcodeproj" -scheme "AttributedString-watchOS" -destination "${{ matrix.destination }}" clean build | xcpretty
#  spm:
#    name: Test with SPM
#    runs-on: macOS-latest
#    env:
#      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
#    steps:
#      - uses: actions/checkout@v2
#      - name: SPM Test
#        run: swift test -c debug
